## MACHINE LEARNING LAB EXPERIMENT 1

### Practising Numpy Commands

In [2]:
import numpy as np

In [20]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])

1


In [8]:
b = np.array([1,2,3,4,5],float)
print(b[1])

2.0


In [9]:
array = [1,2,3,4,-8,-10]
print(np.array(array,float)[::-1])

[-10.  -8.   4.   3.   2.   1.]


In [12]:
print(np.flipud(array))

[-10  -8   4   3   2   1]


In [13]:
print(a.shape)

(3,)


In [17]:
b = np.array([[19,47],[18,46],[22,58]])
print(b,b.shape)

[[19 47]
 [18 46]
 [22 58]] (3, 2)


In [21]:
print(np.reshape(a,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(np.reshape(a,(9,1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [32]:
a.shape = (1,9)
print(a,a[0],type(a),type(a[0]))
a = a[0][:6]

[[1 2 3 4 5 6 7 8 9]] [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [41]:
a.shape = (3,2)
print(a,b,sep="\n\n")

[[1 2]
 [3 4]
 [5 6]]

[[19 47]
 [18 46]
 [22 58]]


In [39]:
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis=1))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [19 47]
 [18 46]
 [22 58]]
[[ 1  2 19 47]
 [ 3  4 18 46]
 [ 5  6 22 58]]


In [44]:
print(np.zeros((1,2)))
print(np.zeros((1,2),dtype=int))
print(np.ones((3,2)))
print(np.ones((3,2),dtype=int))

[[0. 0.]]
[[0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 1]
 [1 1]
 [1 1]]
