## MACHINE LEARNING LAB EXPERIMENT 1

### Practising Numpy Commands

In [18]:
import numpy as np

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])

1


In [20]:
b = np.array([1,2,3,4,5],float)
print(b[1])

2.0


In [21]:
array = [1,2,3,4,-8,-10]
print(np.array(array,float)[::-1])

[-10.  -8.   4.   3.   2.   1.]


In [22]:
print(np.flipud(array))

[-10  -8   4   3   2   1]


In [23]:
print(a.shape)

(9,)


In [24]:
b = np.array([[19,47],[18,46],[22,58]])
print(b,b.shape)

[[19 47]
 [18 46]
 [22 58]] (3, 2)


In [25]:
print(np.reshape(a,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(np.reshape(a,(9,1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [27]:
a.shape = (1,9)
print(a,a[0],type(a),type(a[0]))
a = a[0][:6]

[[1 2 3 4 5 6 7 8 9]] [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [28]:
a.shape = (3,2)
print(a,b,sep="\n\n")

[[1 2]
 [3 4]
 [5 6]]

[[19 47]
 [18 46]
 [22 58]]


In [29]:
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis=1))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [19 47]
 [18 46]
 [22 58]]
[[ 1  2 19 47]
 [ 3  4 18 46]
 [ 5  6 22 58]]


In [30]:
print(np.zeros((1,2)))
print(np.zeros((1,2),dtype=int))
print(np.ones((3,2)))
print(np.ones((3,2),dtype=int))

[[0. 0.]]
[[0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 1]
 [1 1]
 [1 1]]


In [31]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
print(np.eye(3,4),"\n")
print(np.eye(3,4,1),"\n")
print(np.eye(3,4,2),"\n")
print(np.eye(3,4,-1),"\n")
print(np.eye(3,4,-2),"\n")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] 

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]] 



In [50]:
a = np.array([1,2,3,4], float)
b = np.array([5,6,7,8], float)

In [34]:
print(a + b,np.add(a,b),sep="\t")

[ 6.  8. 10. 12.]	[ 6.  8. 10. 12.]


In [35]:
print(np.subtract(a,b))

[-4. -4. -4. -4.]


In [36]:
print(np.divide(a,b))

[0.2        0.33333333 0.42857143 0.5       ]


In [37]:
print(np.power(a,2))

[ 1.  4.  9. 16.]


In [38]:
print(np.mod(a,3))

[1. 2. 0. 1.]


In [51]:
print(np.multiply(a,b))

[ 5. 12. 21. 32.]


In [53]:
print(np.gcd(56,48))

8


In [40]:
a = np.array([ [1, 2], [3, 4],[5,6] ])

In [41]:
print(np.sum(a, axis = 0))        
print(np.sum(a, axis = 1))        
print(np.sum(a, axis = None))     
print(np.sum(a)) 

[ 9 12]
[ 3  7 11]
21
21


In [42]:
print(np.prod(a, axis = 0))        
print(np.prod(a, axis = 1))        
print(np.prod(a, axis = None))     
print(np.prod(a)) 

[15 48]
[ 2 12 30]
720
720


In [43]:
print(np.max(a, axis = 0))        
print(np.max(a, axis = 1))        
print(np.max(a, axis = None))     
print(np.max(a)) 

[5 6]
[2 4 6]
6
6


In [44]:
print(np.min(a, axis = 0))        
print(np.min(a, axis = 1))        
print(np.min(a, axis = None))     
print(np.min(a)) 

[1 2]
[1 3 5]
1
1


In [45]:
print(np.mean(a, axis = 0))        
print(np.mean(a, axis = 1))        
print(np.mean(a, axis = None))     
print(np.mean(a)) 

[3. 4.]
[1.5 3.5 5.5]
3.5
3.5


In [46]:
print(np.var(a, axis = 0))        
print(np.var(a, axis = 1))        
print(np.var(a, axis = None))     
print(np.var(a)) 

[2.66666667 2.66666667]
[0.25 0.25 0.25]
2.9166666666666665
2.9166666666666665


In [47]:
print(np.std(a, axis = 0))        
print(np.std(a, axis = 1))        
print(np.std(a, axis = None))     
print(np.std(a)) 

[1.63299316 1.63299316]
[0.5 0.5 0.5]
1.707825127659933
1.707825127659933
